#!/usr/bin/env bash
# Configure the shared backend for Pharos sessions.
# Usage: bash scripts/setup-codex.sh api|login|status
set -euo pipefail
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
. "$HERE/../scripts/env.sh"
PHAROS_SHARED_CONFIG_HOME="${PHAROS_CODEX_SHARED_HOME:-$PHAROS_RUNTIME/codex-home}"
mkdir -p "$PHAROS_SHARED_CONFIG_HOME"
export PHAROS_CODEX_BIN="${PHAROS_CODEX_BIN:-$(command -v codex || echo codex)}"
umask 077

write_config(){
  cat > "$PHAROS_SHARED_CONFIG_HOME/config.toml" <<EOF
# Generated by scripts/setup-codex.sh.
model = "${PHAROS_CODEX_MODEL:-gpt-6-astra}"
review_model = "${PHAROS_CODEX_MODEL:-gpt-6-astra}"
model_reasoning_effort = "${PHAROS_CODEX_EFFORT:-max}"
disable_response_storage = true
# Each actor loads the contract in its own directory.
project_root_markers = ["AGENTS.md"]
EOF
  if [ "$1" = "api" ]; then
    echo 'model_provider = "OpenAI"' >> "$PHAROS_SHARED_CONFIG_HOME/config.toml"
  fi
  cat >> "$PHAROS_SHARED_CONFIG_HOME/config.toml" <<EOF

[sandbox_workspace_write]
network_access = true

[features]
goals = true

[projects."$PHAROS_ROOT"]
trust_level = "trusted"
EOF
  chmod 600 "$PHAROS_SHARED_CONFIG_HOME/config.toml"
}

write_provider(){
  : "${CODEX_API_BASE_URL:?CODEX_API_BASE_URL not set (config/pharos.env)}"
  if [ "${CODEX_API_PROVIDER:-openai-compatible}" = "azure" ]; then
    : "${CODEX_API_VERSION:?CODEX_API_VERSION not set for Azure (config/pharos.env)}"
    : "${AZURE_OPENAI_API_KEY:?AZURE_OPENAI_API_KEY not set for Azure (config/pharos.env)}"
  else
    : "${OPENAI_API_KEY:?OPENAI_API_KEY not set (config/pharos.env)}"
  fi
  write_config api
  cat >> "$PHAROS_SHARED_CONFIG_HOME/config.toml" <<EOF

[model_providers.OpenAI]
name = "${CODEX_API_PROVIDER:-openai-compatible}"
base_url = "$CODEX_API_BASE_URL"
wire_api = "responses"
request_max_retries = ${CODEX_REQUEST_MAX_RETRIES:-4}
stream_max_retries = ${CODEX_STREAM_MAX_RETRIES:-4}
EOF
  if [ "${CODEX_API_PROVIDER:-openai-compatible}" = "azure" ]; then
    cat >> "$PHAROS_SHARED_CONFIG_HOME/config.toml" <<EOF
query_params = { api-version = "$CODEX_API_VERSION" }
env_http_headers = { "api-key" = "AZURE_OPENAI_API_KEY" }
supports_websockets = false
EOF
  else
    echo 'requires_openai_auth = true' >> "$PHAROS_SHARED_CONFIG_HOME/config.toml"
    printf '%s' "$OPENAI_API_KEY" \
      | env CODEX_HOME="$PHAROS_SHARED_CONFIG_HOME" "$PHAROS_CODEX_BIN" login --with-api-key
  fi
  echo "[setup-codex] wrote $PHAROS_SHARED_CONFIG_HOME/config.toml"
}

case "${1:-status}" in
  api)
    write_provider
    echo "[setup-codex] backend = api. Verify with: pharos check-codex"
    ;;
  login)
    # Subscription login uses the default provider and the same role settings.
    write_config login
    echo "[setup-codex] launching device authentication"
    exec env CODEX_HOME="$PHAROS_SHARED_CONFIG_HOME" "$PHAROS_CODEX_BIN" login --device-auth
    ;;
  status)
    echo "[setup-codex] CODEX_BACKEND=$CODEX_BACKEND  config=$PHAROS_SHARED_CONFIG_HOME"
    if [ -f "$PHAROS_SHARED_CONFIG_HOME/config.toml" ] && grep -q 'model_provider = "OpenAI"' "$PHAROS_SHARED_CONFIG_HOME/config.toml"; then
      echo "  provider: ${CODEX_API_PROVIDER:-openai-compatible} ($CODEX_API_BASE_URL, ${PHAROS_CODEX_MODEL:-gpt-6-astra})"
    else
      env CODEX_HOME="$PHAROS_SHARED_CONFIG_HOME" "$PHAROS_CODEX_BIN" login status
    fi
    ;;
  *) echo "Usage: bash scripts/setup-codex.sh api|login|status" >&2; exit 1 ;;
esac
