"""Project directories, agent configuration, and detached worker-loop launch."""

from __future__ import annotations

import json
import shutil
import os
import tempfile
import re
import socket
import subprocess
import sys
import time
from pathlib import Path
from typing import Dict, List, Optional

from pharos import codex

from . import layout as L


def atomic_write(path: Path, text: str) -> None:
    """Replace a file atomically using a unique temporary file in the same directory."""
    path.parent.mkdir(parents=True, exist_ok=True)
    fd, tmp = tempfile.mkstemp(prefix=path.name + ".", suffix=".tmp", dir=str(path.parent))
    try:
        with os.fdopen(fd, "w", encoding="utf-8") as fh:
            fh.write(text)
        os.replace(tmp, path)
    except BaseException:
        Path(tmp).unlink(missing_ok=True)
        raise


def _toml_str(s: str) -> str:
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'


def symlink(target: Path, link: Path) -> None:
    """Create a symlink if absent, ignoring errors when links cannot be created."""
    if link.is_symlink() or link.exists():
        return
    try:
        os.symlink(target, link)
    except OSError:
        pass


# Use the worker loop's interpreter for the gateway; refresh it on every start.
_CODEX_CONFIG = """\
# Auto-generated by pharos (rewritten each time the worker loop starts); do not hand-edit.
[mcp_servers.pharos]
command = {python}
args = ["-m", "pharos.gateway"]
# Allow fact_submit to wait for a full verification.
tool_timeout_sec = 100000

[mcp_servers.pharos.env]
PHAROS_PROJECT_DIR = {project_dir}
PHAROS_AUTHOR = {author}
PHAROS_ROLE = "worker"
PHAROS_VERIFY_URL = {verify_url}
PHAROS_VERIFY_TIMEOUT = {verify_timeout}
"""

_TASK_PLACEHOLDER = (
    "# Task\n\n(unassigned — the main agent writes your assignment here via "
    "`pharos assign`; you read this file at the start of every round)\n"
)

# expert_guidance/ seeds
_INSTRUCTIONS_SEED = (
    "# Expert instructions — verbatim, append-only\n\n"
    "One entry per instruction: date · channel (launch / main-session dialogue) · "
    "the operator's exact words · one line of reading. Never edit or delete an "
    "entry; a retirement is itself a new entry.\n"
)
_ROUTES_SEED = (
    "# Route board\n\n"
    "No routes yet.\n"
)
_GUIDANCE_SEED = (
    "# Expert guidance — the digest\n\n"
    "No instructions yet.\n\n"
    "## Papers the expert named\n\n"
    "none yet\n\n"
    "## Do not cite / superseded\n\n"
    "none yet\n"
)


def _verify_port_base() -> int:
    """The first port tried when allocating a project's verify port."""
    try:
        return int(os.environ.get("VERIFY_PORT", "") or L.DEFAULT_VERIFY_PORT_BASE)
    except ValueError:
        return L.DEFAULT_VERIFY_PORT_BASE


def _used_verify_ports() -> set:
    """Every ``verify_port`` already claimed by a sibling project.json."""
    used = set()
    root = L.agents_root()
    if root.is_dir():
        for meta in root.glob("*/project.json"):
            try:
                port = json.loads(meta.read_text(encoding="utf-8")).get("verify_port")
            except (json.JSONDecodeError, OSError):
                continue
            if isinstance(port, int):
                used.add(port)
    return used


def port_is_free(port: int, host: str = "127.0.0.1") -> bool:
    """Probe whether ``host:port`` can be bound, releasing the socket immediately."""
    with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as s:
        s.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)
        try:
            s.bind((host, port))
        except OSError:
            return False
    return True


def verify_port_problem(port: int, project: Optional[str] = None) -> Optional[str]:
    """Why ``port`` cannot be this project's verify port — ``None`` when it can.
    Two reasons: a sibling project of this deployment already claims it in its
    project.json, or some process on the host holds it (typically another Pharos
    deployment allocating from the same base)."""
    if not (1024 <= port <= 65535):
        return f"port {port} is outside 1024–65535"
    for meta in (L.agents_root().glob("*/project.json") if L.agents_root().is_dir() else ()):
        if project and meta.parent.name == project:
            continue
        try:
            if json.loads(meta.read_text(encoding="utf-8")).get("verify_port") == port:
                return f"port {port} is already project {meta.parent.name!r}'s verify port"
        except (json.JSONDecodeError, OSError):
            continue
    if not port_is_free(port):
        return (f"port {port} is held by another process on this host — a foreign "
                f"deployment allocating from the same base? (give each deployment its "
                f"own VERIFY_PORT in config/pharos.env)")
    return None


def allocate_verify_port() -> int:
    """Find the lowest free port from the base, excluding sibling project claims."""
    used = _used_verify_ports()
    base = _verify_port_base()
    for port in range(base, base + 1000):
        if port in used or not port_is_free(port):
            continue
        return port
    raise SystemExit(f"no free verify port in {base}–{base + 999}; set VERIFY_PORT to another base")


def set_verify_port(project: str, port: int) -> Dict:
    """Move a project to ``port``: rewrite ``verify_port`` in its project.json.
    The workers' gateway configs pin the verify URL, but ``write_codex_config``
    regenerates them from project.json at every loop start, so nothing else
    needs touching. The caller (``pharos verify port``) makes sure the service is
    down first — a live service keeps its old port."""
    meta_path = L.project_dir(project) / "project.json"
    try:
        meta = json.loads(meta_path.read_text(encoding="utf-8"))
    except OSError:
        raise SystemExit(f"no such project: {project}")
    problem = verify_port_problem(port, project)
    if problem:
        raise SystemExit(problem)
    old = meta.get("verify_port")
    meta["verify_port"] = port
    atomic_write(meta_path, json.dumps(meta, ensure_ascii=False, indent=2))
    return {"project": project, "old_port": old, "verify_port": port}


def project_verify_port(project: str) -> Optional[int]:
    """The project's allocated verify port (from its project.json), if any."""
    meta = L.project_dir(project) / "project.json"
    try:
        port = json.loads(meta.read_text(encoding="utf-8")).get("verify_port")
    except (json.JSONDecodeError, OSError):
        return None
    return port if isinstance(port, int) else None


def _verify_url(project: Optional[str] = None) -> str:
    # Explicit URL, then project port, then the deployment's default port.
    env = os.environ.get("PHAROS_VERIFY_URL")
    if env:
        return env
    port = project_verify_port(project) if project else None
    if port is None:
        port = _verify_port_base()
    return f"http://127.0.0.1:{port}/verify"


def _verify_timeout() -> str:
    # MCP environment values must be TOML strings, even when their consumers
    # parse them as integers.
    return os.environ.get("PHAROS_VERIFY_TIMEOUT", "90000")


def _default_model() -> str:
    return os.environ.get("PHAROS_WORKER_MODEL") or codex.DEFAULT_MODEL


def write_codex_config(wl: "L.WorkerLayout") -> None:
    """Write worker MCP configuration using the current interpreter and project port."""
    atomic_write(wl.codex_config, _CODEX_CONFIG.format(
        python=_toml_str(sys.executable),
        project_dir=_toml_str(str(wl.project_dir)),
        author=_toml_str(wl.name),
        verify_url=_toml_str(_verify_url(wl.project)),
        verify_timeout=_toml_str(_verify_timeout()),
    ))


# Main-agent configuration, pinned to the current interpreter and project.
_MAIN_CODEX_CONFIG = """\
# Auto-generated by `pharos new`; do not hand-edit (regenerate with a new project).
model = {model}
# Main-agent effort is independent of worker and verifier settings.
model_reasoning_effort = "ultra"
review_model = {model}
disable_response_storage = true

[sandbox_workspace_write]
network_access = true

[features]
goals = true

[features.current_time_reminder]
enabled = true
reminder_interval_seconds = 1800
clock_source = "system"
delivery_mode = "after_user_or_tool_output"
sleep_tool = true

[mcp_servers.pharos]
command = {python}
args = ["-m", "pharos.gateway"]
tool_timeout_sec = 100000

[mcp_servers.pharos.env]
PHAROS_ROLE = "main"
PHAROS_AUTHOR = "main_agent"
PHAROS_PROJECT_DIR = {project_dir}
PHAROS_VERIFY_TIMEOUT = {verify_timeout}
"""


def write_main_codex_config(project: str, model: str,
                            into: Optional[Path] = None) -> None:
    """Write a main-role ``.codex/config.toml`` — for the project dir itself
    (the resident main agent) or, via ``into``, for another cwd that runs with
    the main agent's wiring (the ``chat/`` discussion instance). The MCP stays
    pinned to the PROJECT dir either way."""
    pdir = L.project_dir(project)
    atomic_write((into or pdir) / ".codex" / "config.toml", _MAIN_CODEX_CONFIG.format(
        model=_toml_str(model),
        python=_toml_str(sys.executable),
        project_dir=_toml_str(str(pdir)),
        verify_timeout=_toml_str(_verify_timeout()),
    ))


def do_new(project: str, roles: str = "xhigh:3,max:4",
           model: Optional[str] = None, port: Optional[int] = None) -> Dict:
    """Scaffold a project dir + one worker home per role. Refuses to clobber an
    existing project dir (no silent overwrite of a live fact graph). The verify
    port is ``port`` when given (refused if a sibling claims it or the host holds
    it), else the lowest free one at/above the base. Returns
    ``{"project_dir", "workers", "verify_port"}``."""
    pdir = L.project_dir(project)
    if pdir.exists():
        raise SystemExit(f"project already exists: {pdir} (pick another name or remove it)")
    role_pairs = L.parse_roles(roles)
    model = model or _default_model()
    if port is not None:
        problem = verify_port_problem(port)
        if problem:
            raise SystemExit(problem)
        verify_port = port
    else:
        verify_port = allocate_verify_port()

    L.workers_dir(project).mkdir(parents=True, exist_ok=True)
    (pdir / "global_memory").mkdir(exist_ok=True)
    (pdir / "fact_graph").mkdir(exist_ok=True)
    ensure_verifier_home(project)
    L.materials_dir(project).mkdir(exist_ok=True)
    L.subagents_dir(project).mkdir(exist_ok=True)
    # Reports and chat sessions have separate homes; checkpoints use the main session.
    (L.human_report_dir(project) / "md").mkdir(parents=True, exist_ok=True)
    (L.human_report_dir(project) / "pdf").mkdir(parents=True, exist_ok=True)
    L.checkpoints_dir(project).mkdir(exist_ok=True)
    # ROUTES.md: the live route board, seeded once, never overwritten
    if not L.routes_md(project).exists():
        atomic_write(L.routes_md(project), _ROUTES_SEED)
    # Literature files are shared by workers and helpers.
    (L.literature_dir(project) / "papers").mkdir(parents=True, exist_ok=True)
    (L.literature_dir(project) / "notes").mkdir(exist_ok=True)
    # Preserve existing operator instructions when provisioning templates.
    L.expert_guidance_dir(project).mkdir(exist_ok=True)
    for name, seed in (("INSTRUCTIONS.md", _INSTRUCTIONS_SEED),
                       ("GUIDANCE.md", _GUIDANCE_SEED)):
        seed_path = L.expert_guidance_dir(project) / name
        if not seed_path.exists():
            atomic_write(seed_path, seed)
    ensure_style_dir(project)
    L.computation_dir(project).mkdir(exist_ok=True)

    # Worker configs resolve the verifier URL from this metadata.
    meta = {"name": project, "model": model, "roles": roles,
            "workers": [w for w, _ in role_pairs], "verify_port": verify_port,
            "created_at": int(time.time())}
    atomic_write(pdir / "project.json", json.dumps(meta, ensure_ascii=False, indent=2))
    ensure_chat_home(project)          # needs project.json (the model it mirrors)
    ensure_reporter_home(project)

    # The project uses the main-agent contract and skills, with its own session store.
    symlink(L.main_md(), pdir / "AGENTS.md")
    symlink(L.repo_root() / "OPERATOR.md", pdir / "OPERATOR.md")
    (pdir / ".agents").mkdir(exist_ok=True)
    symlink(L.main_skills_dir(), pdir / ".agents" / "skills")
    write_main_codex_config(project, model)
    codex.provision_codex_home(L.main_codex_home(project))

    created: List[str] = []
    for worker, base in role_pairs:
        wl = L.WorkerLayout(L.worker_dir(project, worker))
        wl.local_memory.mkdir(parents=True, exist_ok=True)
        wl.logs.mkdir(exist_ok=True)

        # static contract + skills (symlinks stay in sync with the repo)
        symlink(L.worker_md(), wl.dir / "AGENTS.md")
        (wl.dir / ".agents").mkdir(exist_ok=True)
        symlink(L.worker_skills_dir(), wl.dir / ".agents" / "skills")

        # codex MCP wiring (role=worker) + this worker's own conversation store
        write_codex_config(wl)
        codex.provision_codex_home(wl.codex_home)
        atomic_write(wl.task, _TASK_PLACEHOLDER)
        atomic_write(wl.role,
                     f"MODEL={model}\nREASONING_EFFORT={base}\nROLE={base}\nPHAROS_AUTHOR={worker}\n")
        atomic_write(wl.status,
                     json.dumps({"worker": worker, "state": "created", "round": 0}, indent=2))
        created.append(worker)

    return {"project_dir": str(pdir), "workers": created, "verify_port": verify_port}


# Side actors — report writer, section writers, paper verifiers — run with the
# read-only ``reader`` MCP role pinned to the project, at the neutral tier.
_SIDE_CODEX_CONFIG = """\
# Auto-generated by pharos; do not hand-edit.
model = {model}
disable_response_storage = true

[sandbox_workspace_write]
network_access = true

[mcp_servers.pharos]
command = {python}
args = ["-m", "pharos.gateway"]

[mcp_servers.pharos.env]
PHAROS_ROLE = {role}
PHAROS_AUTHOR = {author}
PHAROS_PROJECT_DIR = {project_dir}
"""


def _project_model(project: str) -> str:
    try:
        return json.loads((L.project_dir(project) / "project.json")
                          .read_text(encoding="utf-8"))["model"]
    except (OSError, json.JSONDecodeError, KeyError):
        return codex.model()


def ensure_side_home(project: str, home: Path, contract: Path, skills: Path,
                     author: str, role: str = "reader") -> Path:
    """Provision one side-actor home (idempotent): contract as AGENTS.md, its
    skills, a role-pinned MCP config, its own session store, a logs dir."""
    if not L.project_dir(project).is_dir():
        raise SystemExit(f"no such project: {project}")
    (home / ".agents").mkdir(parents=True, exist_ok=True)
    symlink(contract, home / "AGENTS.md")
    symlink(skills, home / ".agents" / "skills")
    atomic_write(home / ".codex" / "config.toml", _SIDE_CODEX_CONFIG.format(
        model=_toml_str(_project_model(project)), python=_toml_str(sys.executable),
        role=_toml_str(role), author=_toml_str(author),
        project_dir=_toml_str(str(L.project_dir(project)))))
    codex.provision_codex_home(home / ".codex-home")
    (home / "logs").mkdir(exist_ok=True)
    return home


def ensure_reporter_home(project: str) -> Path:
    return ensure_side_home(project, L.reporter_dir(project), L.contract("reporter"),
                            L.skills("reporter"), author="reporter")


_SECTION_RE = re.compile(r"^[A-Za-z0-9][A-Za-z0-9._-]*$")


def ensure_section_home(project: str, name: str) -> Path:
    """A section writer's home under paper/src/sections/, plus that section's
    own stateful verifier home inside it."""
    if not _SECTION_RE.match(name):
        raise SystemExit(f"bad section name {name!r} (letters, digits, . _ - only)")
    ensure_paper_workspace(project)
    home = ensure_side_home(project, L.section_dir(project, name),
                            L.contract("section_writer"), L.skills("section"),
                            author=f"section:{name}")
    ensure_side_home(project, L.section_verifier_dir(project, name),
                     L.contract("paper_verifier"), L.skills("paper-verify"),
                     author=f"paper_verifier:{name}")
    return home


def ensure_style_dir(project: str) -> Path:
    """``<project>/style/`` — the paper's style layer (the `paper-style`
    skill): README.md (how to customize, copied once from the default package),
    ``default`` -> the repo's default style package, and beside them whatever
    the operator adds (STYLE.md, TEMPLATE.tex, exemplar/). Idempotent; never
    overwrites what is there."""
    sdir = L.style_dir(project)
    sdir.mkdir(parents=True, exist_ok=True)
    default = L.default_style_dir()
    readme = default / "README.md"
    if readme.is_file() and not (sdir / "README.md").exists():
        shutil.copy(readme, sdir / "README.md")
    symlink(default, sdir / "default")
    return sdir


def ensure_paper_workspace(project: str) -> Path:
    """Provision paper sections, the template copy, style files, and verifier home.

    Existing template and style files are preserved.
    """
    pdir = L.paper_dir(project)
    ensure_style_dir(project)
    L.sections_dir(project).mkdir(parents=True, exist_ok=True)
    local, shared = L.paper_src_dir(project) / "template.tex", L.paper_template(project)
    if not local.exists() and shared.is_file():
        shutil.copy(shared, local)
    ensure_side_home(project, L.paper_verifier_dir(project), L.contract("paper_verifier"),
                     L.skills("paper-verify"), author="paper_verifier:global")
    return pdir


def ensure_chat_home(project: str) -> Path:
    """Provision a chat home with main-role tools and a separate session store."""
    pdir = L.project_dir(project)
    if not pdir.is_dir():
        raise SystemExit(f"no such project: {project}")
    cdir = L.chat_dir(project)
    cdir.mkdir(exist_ok=True)
    symlink(L.repo_root() / "agents" / "contracts" / "chat.md", cdir / "AGENTS.md")
    write_main_codex_config(project, _project_model(project), into=cdir)
    codex.provision_codex_home(cdir / ".codex-home")
    return cdir


def ensure_verifier_home(project: str) -> Path:
    """Provision the verifier's contract, skills, sessions, and run logs in its home."""
    home = L.verifier_dir(project)
    home.mkdir(parents=True, exist_ok=True)
    symlink(L.verifier_md(), home / "AGENTS.md")
    (home / ".agents").mkdir(exist_ok=True)
    symlink(L.verify_skills_dir(), home / ".agents" / "skills")
    L.verifier_runs_dir(project).mkdir(exist_ok=True)
    codex.provision_codex_home(L.verifier_codex_home(project))
    return home


_SUB_RE = re.compile(r"^sub[1-9]\d*$")


def ensure_subagent(project: str, name: Optional[str] = None) -> Path:
    """Provision (or reuse) one subagent dir under ``<project>/subagents/``.

    ``name=None`` allocates the next free ``subN`` atomically (mkdir is the
    lock). An explicit ``name`` must match ``subN`` and is created/reused
    idempotently — reuse lets the main agent continue an existing helper.
    Every home gets its own ``.codex-home`` (sessions separate per helper)
    and a ``logs/`` dir for the launcher's stdout captures."""
    if not L.project_dir(project).is_dir():
        raise SystemExit(f"unknown project: {project}")
    root = L.subagents_dir(project)
    root.mkdir(parents=True, exist_ok=True)
    if name is not None:
        if not _SUB_RE.match(name):
            raise SystemExit(f"subagent name must look like sub1/sub2/…, got {name!r}")
        sdir = root / name
        sdir.mkdir(exist_ok=True)
    else:
        n = 1
        while True:
            sdir = root / f"sub{n}"
            try:
                sdir.mkdir()
                break
            except FileExistsError:
                n += 1
    (sdir / "logs").mkdir(exist_ok=True)
    # helpers run the main agent's errands (literature, digests): the read-only
    # reader role gives them theorem search and the truth stores, no writes
    atomic_write(sdir / ".codex" / "config.toml", _SIDE_CODEX_CONFIG.format(
        model=_toml_str(_project_model(project)), python=_toml_str(sys.executable),
        role=_toml_str("reader"), author=_toml_str(sdir.name),
        project_dir=_toml_str(str(L.project_dir(project)))))
    codex.provision_codex_home(sdir / ".codex-home")
    return sdir


def spawn_loop(wdir: Path) -> int:
    """Launch ``python -m pharos.execution <wdir>`` detached in its own process
    group (``start_new_session=True``) so ``pharos stop --force`` can ``killpg``
    the loop *and* its in-flight codex child. Returns the child pid."""
    wl = L.WorkerLayout(wdir)
    wl.logs.mkdir(parents=True, exist_ok=True)
    logf = open(wl.logs / "loop.log", "a", encoding="utf-8")
    try:
        proc = subprocess.Popen(
            [sys.executable, "-m", "pharos.execution", str(wdir)],
            stdout=logf, stderr=subprocess.STDOUT, stdin=subprocess.DEVNULL,
            start_new_session=True, env=L.child_env(),
        )
    finally:
        logf.close()
    return proc.pid
